[[headers]]
for = "/*"
[headers.values]
X-Content-Type-Options = "nosniff"
Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
X-Frame-Options = "SAMEORIGIN"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "microphone 'none'; payment 'none'; geolocation 'none'; midi 'none'; sync-xhr 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'"
Content-Security-Policy = """
    default-src 'self';
    script-src 'self' https://cdn.jsdelivr.net https://tinylytics.app;
    style-src 'self' ;
    font-src 'self';
    img-src 'self' data: https: http: * https://s.gravatar.com;
    connect-src 'self' https:;
    media-src 'self';
    object-src 'none';
    frame-src 'self';
    frame-ancestors 'self';
    form-action 'self';
    base-uri 'self';
    upgrade-insecure-requests;"""
X-XSS-Protection = "1; mode=block"


# Cache Control for Static Assets

[[headers]]
for = "/*.js"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.css"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.jpg"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.svg"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.png"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"


[[headers]]
for = "/*.webp"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/og.png"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Methods = "*"
Access-Control-Allow-Headers = "*"

[[headers]]
for = "/og.mp4"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Methods = "*"
Access-Control-Allow-Headers = "*"

[[headers]]
for = "/"
[headers.values]
Cache-Control = "public, max-age=3600"


[[redirects]]
from = "/hiromi"
to = "https://linkedin.com/in/hiromi"
status = 302

[build]
  command = "npm run build"
  publish = "dist"
